def create_table(name) :
    cmd = "CREATE TABLE " + name + """(
    Date                             DATE  NOT NULL PRIMARY KEY
    ,activisioninc                    FLOAT    
    ,adobesysinc                      FLOAT   
    ,autodataprocess                  FLOAT   
    ,alexionpharmaceuticalsinc        FLOAT  
    ,aligntechnology                  FLOAT   
    ,googleinc                        FLOAT   
    ,googleincc                       FLOAT   
    ,amazoncominc                     FLOAT   
    ,advmicrodevice                   FLOAT   
    ,americanairlinesgroup            FLOAT   
    ,amgeninc                         FLOAT   
    ,citigroup                        FLOAT   
    ,applecomputerinc                 FLOAT   
    ,appliedmatlsinc                  FLOAT   
    ,asmlholdings                     FLOAT   
    ,autodeskinc                      FLOAT   
    ,baiducom                         FLOAT   
    ,biogenidecinc                    FLOAT   
    ,biomarinpharmaceuticals          FLOAT   
    ,pricelinecominc                  FLOAT   
    ,avagotechnologies                FLOAT   
    ,cadencedesignsysteminc           FLOAT   
    ,celgenecorp                      FLOAT   
    ,cernercorporatio                 FLOAT   
    ,chartercommunications            FLOAT   
    ,checkpointsoftwaretechlt         FLOAT   
    ,cintascorp                       FLOAT   
    ,ciscosysinc                      FLOAT   
    ,citrixsysinc                     FLOAT   
    ,cognizanttechnologysolutio       FLOAT   
    ,comcastcorpnew                   FLOAT   
    ,costcowhslcorpnew                FLOAT   
    ,csxcorp                          FLOAT   
    ,ctripcominternational            FLOAT   
    ,dollartreeinc                    FLOAT   
    ,ebayinc                          FLOAT   
    ,electronicartsinc                FLOAT   
    ,expedia                          FLOAT   
    ,facebookinc                      FLOAT   
    ,fastenalco                       FLOAT   
    ,fiservinc                        FLOAT   
    ,foxcorp                          FLOAT   
    ,foxcorpb                         FLOAT   
    ,gileadsciencesinc                FLOAT   
    ,hasbroinc                        FLOAT   
    ,henryschein                      FLOAT   
    ,idexxlaboratorie                 FLOAT   
    ,illuminainc                      FLOAT   
    ,incytecorp                       FLOAT   
    ,intelcorp                        FLOAT   
    ,intuit                           FLOAT   
    ,intuitivesurgicalinc             FLOAT   
    ,jbhunttranspo                    FLOAT   
    ,jdcomincadr                      FLOAT   
    ,klatencorcorp                    FLOAT   
    ,raftfoodsinc                     FLOAT   
    ,lamresearchcorp                  FLOAT   
    ,libertyglobalinc                 FLOAT   
    ,libertyglobalc                   FLOAT   
    ,lululemonathletica               FLOAT   
    ,marriottintl                     FLOAT   
    ,maximintegrated                  FLOAT   
    ,mercadolibre                     FLOAT   
    ,microchiptechnologyinc           FLOAT   
    ,microntech                       FLOAT   
    ,microsoftcorp                    FLOAT   
    ,mondelezinternationalinc         FLOAT   
    ,monsterbeverage                  FLOAT   
    ,mylaninc                         FLOAT   
    ,networkapplianceinc              FLOAT   
    ,neteasecom                       FLOAT   
    ,netflixinc                       FLOAT   
    ,nvidiacorp                       FLOAT   
    ,nxpsemiconductors                FLOAT   
    ,oreillyautomotive                FLOAT   
    ,paccarinc                        FLOAT   
    ,paychexinc                       FLOAT   
    ,paypalholdingsinc                FLOAT   
    ,pepsico                          FLOAT   
    ,qualcomminc                      FLOAT   
    ,regeneronphar                    FLOAT   
    ,rossstoresinc                    FLOAT   
    ,siriussatelliteradioinc          FLOAT   
    ,skyworkssolutionsinc             FLOAT   
    ,starbuckscorp                    FLOAT   
    ,symanteccorp                     FLOAT   
    ,synopsysinc                      FLOAT   
    ,metropcscommunications           FLOAT   
    ,taketwointeractive               FLOAT   
    ,teslamotors                      FLOAT   
    ,texasinstru                      FLOAT   
    ,ultasaloncosmeticsfragrance      FLOAT   
    ,unitedcontinenta                 FLOAT   
    ,verisigninc                      FLOAT   
    ,veriskanalyticsinc               FLOAT   
    ,vertexpharm                      FLOAT   
    ,walgreenco                       FLOAT   
    ,westerndigital                   FLOAT   
    ,willisgroupholdingsplc           FLOAT   
    ,workdayinc                       FLOAT   
    ,wynnresortsltd                   FLOAT   
    ,xcelenergy                       FLOAT   
    ,xilinxinc                        FLOAT   
    ,mmm                              FLOAT   
    ,abbottlaboratories               FLOAT   
    ,accentureltd                     FLOAT   
    ,americanintlgroup                FLOAT   
    ,actavis                          FLOAT   
    ,altriagroup                      FLOAT   
    ,att                              FLOAT   
    ,bakerhughes                      FLOAT   
    ,bankofamerica                    FLOAT   
    ,bkofny                           FLOAT   
    ,baxterintl                       FLOAT   
    ,berkshirehathaway                FLOAT   
    ,boeingco                         FLOAT   
    ,bristolmyersquiib                FLOAT   
    ,caterpillar                      FLOAT   
    ,cocacolaco                       FLOAT   
    ,colgatepalmo                     FLOAT   
    ,corninginc                       FLOAT   
    ,danahercorp                      FLOAT   
    ,deereco                          FLOAT   
    ,devonenergy                      FLOAT   
    ,dominionres                      FLOAT   
    ,dupont                           FLOAT   
    ,dukeenergy                       FLOAT   
    ,elilillyandco                    FLOAT   
    ,emersonelec                      FLOAT   
    ,eogresources                     FLOAT   
    ,exeloncorp                       FLOAT  
    ,exxonmobil                       FLOAT   
    ,fedexcorp                        FLOAT   
    ,fordmotorco                      FLOAT   
    ,franklinres                      FLOAT   
    ,freeportmcm                      FLOAT   
    ,generaldynam                     FLOAT   
    ,generalelectric                  FLOAT   
    ,generalmills                     FLOAT   
    ,genmotors                        FLOAT   
    ,goldmansachsgroup                FLOAT   
    ,halliburtonco                    FLOAT   
    ,homedepot                        FLOAT   
    ,honeywellintl                    FLOAT   
    ,hewlettpack                      FLOAT   
    ,ibm                              FLOAT   
    ,illinoistoolwkr                  FLOAT   
    ,johnsonjohnson                   FLOAT   
    ,jpmorganchase                    FLOAT   
    ,kimberlyclark                    FLOAT   
    ,lasvegassands                    FLOAT   
    ,lockheedmartin                   FLOAT   
    ,lowescompanies                   FLOAT   
    ,mastercardcla                    FLOAT   
    ,mcdonalds                        FLOAT   
    ,merckco                          FLOAT   
    ,metlifeinc                       FLOAT   
    ,morganstanley                    FLOAT   
    ,ntloilwellvarc                   FLOAT   
    ,newmontmining                    FLOAT   
    ,nike                             FLOAT   
    ,occidentalpetro                  FLOAT   
    ,pfizer                           FLOAT   
    ,philipmorrisintl                 FLOAT   
    ,pncfinserv                       FLOAT   
    ,proctergamble                    FLOAT   
    ,prudentialfin                    FLOAT   
    ,schlumbergerltd                  FLOAT   
    ,simonpropgrp                     FLOAT   
    ,southernco                       FLOAT   
    ,southerncoppercorp               FLOAT   
    ,target                           FLOAT   
    ,thetravelersco                   FLOAT   
    ,unionpacific                     FLOAT   
    ,unitedparcel                     FLOAT   
    ,unitedtech                       FLOAT   
    ,unitedhealthgroup                FLOAT   
    ,usbancorp                        FLOAT   
    ,verizoncommunications            FLOAT   
    ,visainc                          FLOAT   
    ,walmartstores                    FLOAT   
    ,disney                           FLOAT   
    ,wellsfargo                       FLOAT   
    ,yumbrandsinc                     FLOAT   
    );"""

    return cmd
